### ISSUE TITLE
ドキュメントを整える

### ISSUE THREAD

**Issue by y-ma3** [school-interview/school-interview-system#210]
### 関連するもの

Other

### タスクの種類

Improvement

### 概要

* `unity`ディレクトリの`README.md`を更新する
* ルート直下の`README.md`も↑に合わせて更新する
* このタスク内で`client`の`README.md`も最新の情報に更新したい

**Comment by dan848484** [comment]
今日ちょっと話していた英語と日本語のドキュメントどうしましょうかね、、

**Comment by y-ma3** [comment]
@dan848484 一旦、引き継ぎ者がいるかもわからない状態なんで今あるものはキープで。引き継ぎ者がいると確定したときに管理のしやすやを考慮して英語版を削除する。くらいの方針でどうでしょう？
